name: worker 

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3
    
    - name: Setup Go environment
      uses: actions/setup-go@v4.0.1
      with:
        go-version: '1.20.5'
    
    - name: Setup Go bin cache
      uses: actions/cache@v3
      with:
        path: ~/go/bin
        key: ${{ runner.os }}-golang-${{ hashFiles('**/Makefile') }}
        restore-keys: |
         ${{ runner.os }}-golang-
    
    - name: Install tools
      run: make tools
    
    - name: Run tests
      run: make test
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with: 
        files: reports/coverage.out
