name: worker 

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3
    
    - name: Setup Go environment
      uses: actions/setup-go@v4.0.1
      with:
        go-version: '1.20.5'
    
    - name: Install tools
      run: make tools
    
    - name: Run tests
      run: make test

